name: Code review
on: [ push, workflow_dispatch ]
permissions:
  contents: read
jobs:
  code-review:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install Anthropic package
        run: pip install anthropic==0.*
      - name: Serialise site code
        # Get the codebase and save to a file
        # https://manpages.ubuntu.com/manpages/noble/man1/find.1.html
        run: |          
          find src -type f -name "*.py" -print -exec cat {} \; > ${{ runner.temp }}/all_code.txt
          head ${{ runner.temp }}/all_code.txt
      - name: Code review
        # Get Claude to review the code and suggest changes (write a patch file)
        run: |
          cat ${{ runner.temp }}/all_code.txt | python -m scripts.code_review > ${{ runner.temp }}/diff.patch
          head ${{ runner.temp }}/diff.patch
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      # https://manpages.ubuntu.com/manpages/noble/man1/patch.1.html
      - name: Apply patch
        run: patch < ${{ runner.temp }}/diff.patch
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.6
