# Publish to the Python Package Index (PyPI)
# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python#publishing-to-pypi
name: Publish Python Package

# Run on each release
on:
  release:
    types: [ published ]

jobs:
  # Build package
  # https://packaging.python.org/en/latest/tutorials/packaging-projects/#generating-distribution-archives
  build:
    runs-on: ubuntu-24.04
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install build tool
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
      - name: Build a binary wheel and a source tarball
        run: python -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
          if-no-files-found: error

  pypi-publish:
    runs-on: ubuntu-24.04
    needs:
      - build
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/balance-subscriber
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.2
