# GitHub Actions workflow for linting the systemd unit files
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
name: Lint systemd units
on: [ push ]
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install systemdlint
        run: pip install systemdlint
      - name: Lint systemd units
        run: systemdtlint ./systemd/*
