# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Automatic tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read

jobs:
  # Automatic tests
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # Test upcoming versions
        # https://devguide.python.org/versions/
        python-version: [ "3.12", "3.13" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Lint with flake8
        run: flake8
      - run: pytest
      - name: Lint shell scripts
        run: shellcheck *.sh
